[workspace]
members = [
    "xtask",
    "kernel",
    "console",
    "utils",
    "linker",
    "config",
    "fast-trap",
    "vmm",
    "task",
    "vdso",
    "syscall",
    "syscall/syscall_macro",
]
default-members = ["xtask"]

