[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sbi-rt = { git = "https://github.com/rustsbi/sbi-rt", branch = "dev" }
printlib = { path = "../printlib" }
up = { path = "../up" }
r0 = "1.0.0"
buddy-allocator = { git = "https://github.com/YdrMaster/buddy-allocator", rev = "fae1979" }
riscv = "0.8.0"

